name: Build OpenWrt

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * ?"

jobs:
  build_openwrt:
    name: Build OpenWrt
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup build environment
        run: |
         sudo apt update -y && sudo apt upgrade -y
         sudo apt install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5 -y

      - name: Pull OpenWrt-22.03
        run: |
         git clone -b openwrt-22.03 https://github.com/openwrt/openwrt.git
       

      - name: Update feeds
        run: |
            run: |
              cd openwrt
              cat >> feeds.conf.default <<EOF
              src-git openclash https://github.com/vernesong/OpenClash.git
              EOF
              ./scripts/feeds update -a
              ./scripts/feeds install -a


      - name: Make config
        run: |
         cd openwrt
         rm -f ./.config*
         touch ./.config

         cat >> .config <<EOF

         CONFIG_TARGET_x86=y
         CONFIG_TARGET_x86_64=y
         CONFIG_TARGET_x86_64_DEVICE_generic=y
         CONFIG_ARIA2_BITTORRENT=y
         CONFIG_ARIA2_NOXML=y
         CONFIG_ARIA2_OPENSSL=y
         CONFIG_ARIA2_WEBSOCKET=y
         CONFIG_COREMARK_OPTIMIZE_O3=y
         # CONFIG_DOWNLOAD_CHECK_CERTIFICATE is not set
         CONFIG_DRIVER_11AC_SUPPORT=y
         CONFIG_DRIVER_11N_SUPPORT=y
         CONFIG_GNUTLS_ALPN=y
         CONFIG_GNUTLS_ANON=y
         CONFIG_GNUTLS_DTLS_SRTP=y
         CONFIG_GNUTLS_HEARTBEAT=y
         CONFIG_GNUTLS_OCSP=y
         CONFIG_GNUTLS_PSK=y
         # CONFIG_GRUB_IMAGES is not set
         CONFIG_ISO_IMAGES=y
         CONFIG_LIBCURL_COOKIES=y
         CONFIG_LIBCURL_FILE=y
         CONFIG_LIBCURL_FTP=y
         CONFIG_LIBCURL_HTTP=y
         CONFIG_LIBCURL_MBEDTLS=y
         CONFIG_LIBCURL_NGHTTP2=y
         CONFIG_LIBCURL_NO_SMB="!"
         CONFIG_LIBCURL_PROXY=y
         CONFIG_LUCI_LANG_zh_Hans=y
         CONFIG_OPENSSL_ENGINE=y
         CONFIG_OPENSSL_OPTIMIZE_SPEED=y
         CONFIG_OPENSSL_WITH_ASM=y
         CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
         CONFIG_OPENSSL_WITH_CMS=y
         CONFIG_OPENSSL_WITH_DEPRECATED=y
         CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
         CONFIG_OPENSSL_WITH_PSK=y
         CONFIG_OPENSSL_WITH_SRP=y
         CONFIG_OPENSSL_WITH_TLS13=y
         CONFIG_PACKAGE_MAC80211_DEBUGFS=y
         CONFIG_PACKAGE_MAC80211_MESH=y
         CONFIG_PACKAGE_adblock=y
         CONFIG_PACKAGE_aria2=y
         CONFIG_PACKAGE_attr=y
         CONFIG_PACKAGE_avahi-dbus-daemon=y
         CONFIG_PACKAGE_bash=y
         CONFIG_PACKAGE_ca-certificates=y
         CONFIG_PACKAGE_cgi-io=y
         CONFIG_PACKAGE_collectd=y
         CONFIG_PACKAGE_collectd-mod-cpu=y
         CONFIG_PACKAGE_collectd-mod-interface=y
         CONFIG_PACKAGE_collectd-mod-iwinfo=y
         CONFIG_PACKAGE_collectd-mod-load=y
         CONFIG_PACKAGE_collectd-mod-memory=y
         CONFIG_PACKAGE_collectd-mod-network=y
         CONFIG_PACKAGE_collectd-mod-rrdtool=y
         CONFIG_PACKAGE_coremark=y
         CONFIG_PACKAGE_coreutils=y
         CONFIG_PACKAGE_coreutils-nohup=y
         CONFIG_PACKAGE_coreutils-sort=y
         CONFIG_PACKAGE_curl=y
         CONFIG_PACKAGE_dbus=y
         CONFIG_PACKAGE_ddns-scripts=y
         CONFIG_PACKAGE_ddns-scripts-services=y
         # CONFIG_PACKAGE_dnsmasq is not set
         CONFIG_PACKAGE_dnsmasq-full=y
         CONFIG_PACKAGE_dnsmasq_full_auth=y
         CONFIG_PACKAGE_dnsmasq_full_conntrack=y
         CONFIG_PACKAGE_dnsmasq_full_dhcp=y
         CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
         CONFIG_PACKAGE_dnsmasq_full_dnssec=y
         CONFIG_PACKAGE_dnsmasq_full_ipset=y
         CONFIG_PACKAGE_dnsmasq_full_noid=y
         CONFIG_PACKAGE_dnsmasq_full_tftp=y
         CONFIG_PACKAGE_docker=y
         CONFIG_PACKAGE_etherwake=y
         CONFIG_PACKAGE_frpc=y
         CONFIG_PACKAGE_hd-idle=y
         CONFIG_PACKAGE_hostapd=y
         CONFIG_PACKAGE_hostapd-common=y
         CONFIG_PACKAGE_ip-full=y
         CONFIG_PACKAGE_ipset=y
         CONFIG_PACKAGE_iw=y
         CONFIG_PACKAGE_iwinfo=y
         CONFIG_PACKAGE_iwlwifi-firmware-iwl8265=y
         CONFIG_PACKAGE_kmod-cfg80211=y
         CONFIG_PACKAGE_kmod-crypto-acompress=y
         CONFIG_PACKAGE_kmod-crypto-aead=y
         CONFIG_PACKAGE_kmod-crypto-arc4=y
         CONFIG_PACKAGE_kmod-crypto-ccm=y
         CONFIG_PACKAGE_kmod-crypto-cmac=y
         CONFIG_PACKAGE_kmod-crypto-ctr=y
         CONFIG_PACKAGE_kmod-crypto-des=y
         CONFIG_PACKAGE_kmod-crypto-ecb=y
         CONFIG_PACKAGE_kmod-crypto-gcm=y
         CONFIG_PACKAGE_kmod-crypto-gf128=y
         CONFIG_PACKAGE_kmod-crypto-ghash=y
         CONFIG_PACKAGE_kmod-crypto-hmac=y
         CONFIG_PACKAGE_kmod-crypto-kpp=y
         CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
         CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
         CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
         CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
         CONFIG_PACKAGE_kmod-crypto-manager=y
         CONFIG_PACKAGE_kmod-crypto-md4=y
         CONFIG_PACKAGE_kmod-crypto-md5=y
         CONFIG_PACKAGE_kmod-crypto-null=y
         CONFIG_PACKAGE_kmod-crypto-rng=y
         CONFIG_PACKAGE_kmod-crypto-seqiv=y
         CONFIG_PACKAGE_kmod-crypto-sha256=y
         CONFIG_PACKAGE_kmod-crypto-sha512=y
         CONFIG_PACKAGE_kmod-dnsresolver=y
         CONFIG_PACKAGE_kmod-fs-btrfs=y
         CONFIG_PACKAGE_kmod-fs-cifs=y
         CONFIG_PACKAGE_kmod-fs-configfs=y
         CONFIG_PACKAGE_kmod-fs-exfat=y
         CONFIG_PACKAGE_kmod-fs-ext4=y
         CONFIG_PACKAGE_kmod-fs-nfs=y
         CONFIG_PACKAGE_kmod-fs-nfs-common=y
         CONFIG_PACKAGE_kmod-fs-nfs-v4=y
         CONFIG_PACKAGE_kmod-fs-squashfs=y
         CONFIG_PACKAGE_kmod-inet-diag=y
         CONFIG_PACKAGE_kmod-ipt-core=y
         CONFIG_PACKAGE_kmod-ipt-ipset=y
         CONFIG_PACKAGE_kmod-iwlwifi=y
         CONFIG_PACKAGE_kmod-lib-crc16=y
         CONFIG_PACKAGE_kmod-lib-lzo=y
         CONFIG_PACKAGE_kmod-lib-raid6=y
         CONFIG_PACKAGE_kmod-lib-xor=y
         CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
         CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
         CONFIG_PACKAGE_kmod-lib-zstd=y
         CONFIG_PACKAGE_kmod-mac80211=y
         CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
         CONFIG_PACKAGE_kmod-nf-ipt=y
         CONFIG_PACKAGE_kmod-oid-registry=y
         CONFIG_PACKAGE_kmod-phy-ax88796b=y
         CONFIG_PACKAGE_kmod-scsi-core=y
         CONFIG_PACKAGE_kmod-tun=y
         CONFIG_PACKAGE_kmod-udptunnel4=y
         CONFIG_PACKAGE_kmod-udptunnel6=y
         CONFIG_PACKAGE_kmod-usb-core=y
         CONFIG_PACKAGE_kmod-usb-ehci=y
         CONFIG_PACKAGE_kmod-usb-net=y
         CONFIG_PACKAGE_kmod-usb-net-asix=y
         CONFIG_PACKAGE_kmod-usb-storage=y
         CONFIG_PACKAGE_kmod-usb-storage-extras=y
         CONFIG_PACKAGE_kmod-usb-storage-uas=y
         CONFIG_PACKAGE_kmod-usb-xhci-hcd=y
         CONFIG_PACKAGE_kmod-usb2=y
         CONFIG_PACKAGE_kmod-usb2-pci=y
         CONFIG_PACKAGE_kmod-usb3=y
         CONFIG_PACKAGE_kmod-wireguard=y
         CONFIG_PACKAGE_libatomic=y
         CONFIG_PACKAGE_libattr=y
         CONFIG_PACKAGE_libavahi-client=y
         CONFIG_PACKAGE_libavahi-dbus-support=y
         CONFIG_PACKAGE_libbpf=y
         CONFIG_PACKAGE_libcap=y
         CONFIG_PACKAGE_libcap-bin=y
         CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
         CONFIG_PACKAGE_libcurl=y
         CONFIG_PACKAGE_libdaemon=y
         CONFIG_PACKAGE_libdb47=y
         CONFIG_PACKAGE_libdbus=y
         CONFIG_PACKAGE_libelf=y
         CONFIG_PACKAGE_libexpat=y
         CONFIG_PACKAGE_libgmp=y
         CONFIG_PACKAGE_libgnutls=y
         CONFIG_PACKAGE_libipset=y
         CONFIG_PACKAGE_libiwinfo=y
         CONFIG_PACKAGE_libiwinfo-data=y
         CONFIG_PACKAGE_libiwinfo-lua=y
         CONFIG_PACKAGE_libltdl=y
         CONFIG_PACKAGE_liblua=y
         CONFIG_PACKAGE_liblucihttp=y
         CONFIG_PACKAGE_liblucihttp-lua=y
         CONFIG_PACKAGE_libmbedtls=y
         CONFIG_PACKAGE_libmount=y
         CONFIG_PACKAGE_libncurses=y
         CONFIG_PACKAGE_libnetfilter-conntrack=y
         CONFIG_PACKAGE_libnettle=y
         CONFIG_PACKAGE_libnfnetlink=y
         CONFIG_PACKAGE_libnghttp2=y
         CONFIG_PACKAGE_libopenssl=y
         CONFIG_PACKAGE_libpopt=y
         CONFIG_PACKAGE_libreadline=y
         CONFIG_PACKAGE_librrd1=y
         CONFIG_PACKAGE_libruby=y
         CONFIG_PACKAGE_libstdcpp=y
         CONFIG_PACKAGE_libtasn1=y
         CONFIG_PACKAGE_libtirpc=y
         CONFIG_PACKAGE_libubus-lua=y
         CONFIG_PACKAGE_libuci-lua=y
         CONFIG_PACKAGE_liburing=y
         CONFIG_PACKAGE_libuv=y
         CONFIG_PACKAGE_libwebsockets-full=y
         CONFIG_PACKAGE_libyaml=y
         CONFIG_PACKAGE_lsblk=y
         CONFIG_PACKAGE_lua=y
         CONFIG_PACKAGE_luci=y
         CONFIG_PACKAGE_luci-app-adblock=y
         CONFIG_PACKAGE_luci-app-advanced-reboot=y
         CONFIG_PACKAGE_luci-app-aria2=y
         CONFIG_PACKAGE_luci-app-commands=y
         CONFIG_PACKAGE_luci-app-ddns=y
         CONFIG_PACKAGE_luci-app-dockerman=y
         CONFIG_PACKAGE_luci-app-firewall=y
         CONFIG_PACKAGE_luci-app-frpc=y
         CONFIG_PACKAGE_luci-app-hd-idle=y
         CONFIG_PACKAGE_luci-app-openclash=y
         CONFIG_PACKAGE_luci-app-opkg=y
         CONFIG_PACKAGE_luci-app-samba4=y
         CONFIG_PACKAGE_luci-app-statistics=y
         CONFIG_PACKAGE_luci-app-ttyd=y
         CONFIG_PACKAGE_luci-app-wireguard=y
         CONFIG_PACKAGE_luci-app-wol=y
         CONFIG_PACKAGE_luci-base=y
         CONFIG_PACKAGE_luci-compat=y
         CONFIG_PACKAGE_luci-i18n-adblock-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-advanced-reboot-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-commands-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-statistics-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-wireguard-zh-cn=y
         CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y
         CONFIG_PACKAGE_luci-lib-base=y
         CONFIG_PACKAGE_luci-lib-docker=y
         CONFIG_PACKAGE_luci-lib-ip=y
         CONFIG_PACKAGE_luci-lib-ipkg=y
         CONFIG_PACKAGE_luci-lib-jsonc=y
         CONFIG_PACKAGE_luci-lib-nixio=y
         CONFIG_PACKAGE_luci-mod-admin-full=y
         CONFIG_PACKAGE_luci-mod-network=y
         CONFIG_PACKAGE_luci-mod-status=y
         CONFIG_PACKAGE_luci-mod-system=y
         CONFIG_PACKAGE_luci-proto-ipv6=y
         CONFIG_PACKAGE_luci-proto-ppp=y
         CONFIG_PACKAGE_luci-proto-wireguard=y
         CONFIG_PACKAGE_luci-theme-bootstrap=y
         CONFIG_PACKAGE_luci-theme-material=y
         CONFIG_PACKAGE_netdata=y
         CONFIG_PACKAGE_rpcd=y
         CONFIG_PACKAGE_rpcd-mod-file=y
         CONFIG_PACKAGE_rpcd-mod-iwinfo=y
         CONFIG_PACKAGE_rpcd-mod-luci=y
         CONFIG_PACKAGE_rpcd-mod-rrdns=y
         CONFIG_PACKAGE_rrdtool1=y
         CONFIG_PACKAGE_ruby=y
         CONFIG_PACKAGE_ruby-bigdecimal=y
         CONFIG_PACKAGE_ruby-date=y
         CONFIG_PACKAGE_ruby-dbm=y
         CONFIG_PACKAGE_ruby-digest=y
         CONFIG_PACKAGE_ruby-enc=y
         CONFIG_PACKAGE_ruby-forwardable=y
         CONFIG_PACKAGE_ruby-pstore=y
         CONFIG_PACKAGE_ruby-psych=y
         CONFIG_PACKAGE_ruby-stringio=y
         CONFIG_PACKAGE_ruby-strscan=y
         CONFIG_PACKAGE_ruby-yaml=y
         CONFIG_PACKAGE_samba4-libs=y
         CONFIG_PACKAGE_samba4-server=y
         CONFIG_PACKAGE_terminfo=y
         CONFIG_PACKAGE_ttyd=y
         CONFIG_PACKAGE_uhttpd=y
         CONFIG_PACKAGE_uhttpd-mod-ubus=y
         CONFIG_PACKAGE_unzip=y
         CONFIG_PACKAGE_wireguard-tools=y
         CONFIG_PACKAGE_wireless-regdb=y
         CONFIG_PACKAGE_wpa-supplicant=y
         CONFIG_PACKAGE_wsdd2=y
         CONFIG_PACKAGE_zlib=y
         CONFIG_SAMBA4_SERVER_AVAHI=y
         CONFIG_SAMBA4_SERVER_NETBIOS=y
         CONFIG_SAMBA4_SERVER_VFS=y
         CONFIG_SAMBA4_SERVER_WSDD2=y
         # CONFIG_SIGNATURE_CHECK is not set
         CONFIG_TARGET_KERNEL_PARTSIZE=32
         # CONFIG_TARGET_ROOTFS_EXT4FS is not set
         CONFIG_TARGET_ROOTFS_PARTSIZE=168
         # CONFIG_TARGET_ROOTFS_TARGZ is not set
         CONFIG_VHDX_IMAGES=y
         CONFIG_WPA_MSG_MIN_PRIORITY=3


      - name: Build OpenWrt
        run: |
         cd openwrt

         make defconfig
         make download -j8
         make V=s -j$(nproc)

    
      - name: Upload release asset
        if: github.event == 'release'
        run: cd openwrt
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./bin/targets/x86/64/*
          tag: ${{ github.ref }}
          file_glob: true





